import type { Metadata } from "next";
import { Inter, Geist } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import { ThemeProvider } from "@/components/theme/theme-provider";
import Navbar from "@/components/shared/Navbar";

const geist = Geist({ subsets: ['latin'], variable: '--font-sans' });

const inter = Inter({
  weight: ['400', '500', '600', '700', '800', '900'],
  subsets: ['latin']
})

export const metadata: Metadata = {
  title: "Shoriful Islam",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      suppressHydrationWarning
      className={cn("h-full", "antialiased", inter.className, "font-sans", geist.variable)}
    >
      <body
        className="min-h-full flex flex-col">
        <ThemeProvider
          attribute='class'
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >

          <Navbar />
          
          <main>
            {children}
          </main>

        </ThemeProvider>

      </body>
    </html>
  );
}
